Отрисуй меня полностью (часть 1)
htmlacademy-javascript/1652259-keksobooking-24 pull request #5
Opened 2021-10-18 13:54 UTC by DariaAkimova

---
:mortar_board: [Отрисуй меня полностью (часть 1)](https://up.htmlacademy.ru/javascript/24/user/1652259/tasks/12)

2021-10-18 14:06 UTC, DariaAkimova commented on js/generate-elements.js
> +
Не получается вставить все фотографии из массива dataForCard.offer.photos.length, всегда только одна.

2021-10-18 14:06 UTC, DariaAkimova commented on js/generate-elements.js
> +
Не видит src, фото не вставляется.

2021-10-19 09:05 UTC, ArtemVeremienko commented
Не забывай обновлять мастер и [затем начинать новую ветку](https://github.com/htmlacademy-javascript/1652259-keksobooking-24/blob/master/Contributing.md#2-%D0%BF%D1%80%D0%B5%D0%B6%D0%B4%D0%B5-%D1%87%D0%B5%D0%BC-%D0%BF%D1%80%D0%B8%D1%81%D1%82%D1%83%D0%BF%D0%B0%D1%82%D1%8C-%D0%BA-%D0%BD%D0%BE%D0%B2%D0%BE%D0%BC%D1%83-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D1%8E-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D0%B5-master)

2021-10-20 16:42 UTC, ArtemVeremienko commented on js/data.js
> +console.log (createAllOffers());
это лучше убрать, потому что здесь вызывается функция и после неё массив с аватарами пустой

2021-11-01 16:24 UTC, ArtemVeremienko commented on js/generate-elements.js
> +
> Какой массив взять? Я пробовала сделать так, но получилось как-то совсем примитивно и все равно не работает. (это все записала в самом конце перед экспортом)

Рабочее, но примитивное - лучше идеального и не рабочего.
Что именно не работает?

2021-11-01 16:31 UTC, ArtemVeremienko commented on js/generate-elements.js
> +
> allFields.forEach((someField) => {
if (someField.tagName === 'img' && someField.src=== undefined
||
someField.textContent === undefined)
{someField.classList.add('hidden');}
});

посмотри справку по свойству `tagName` в нём будет имя прописными буквами. Это условие можно привести к такому виду:

```js
allFields.forEach((someField) => {
  if (someField.tagName === 'IMG' && !someField.src || !someField.textContent) {
    someField.classList.add('hidden');
  }
});
```

2021-11-01 16:33 UTC, ArtemVeremienko commented on js/generate-elements.js
> +
> Может, я не в ту сторону думаю вообще и эту часть задания надо иначе выполнять? Потому что в том виде, в котором код сейчас есть, он не работает - hidden не появляется в нужном месте, если данные убрать где-то.

Почти любую задачу можно выполнить разными спосбами. Главное чтобы тебе был близок этот подход.

2021-11-01 16:52 UTC, ArtemVeremienko commented on js/generate-elements.js
> +
const setOfferTypeText = (offerType, offerElement) => {
    switch (offerType) {
    case  'flat':
      offerElement.textContent = 'Квартира';
      break;
    case 'bungalow':
      offerElement.textContent = 'Бунгало';
      break;
    case 'house':
      offerElement.textContent = 'Дом';
      break;
    case 'palace':
     offerElement.textContent = 'Дворец';
      break;
    case 'hotel':
      offerElement.textContent = 'Отель';
      break;
  }
}

2021-11-01 18:05 UTC, DariaAkimova commented on js/generate-elements.js
> +
> посмотри справку по свойству `tagName` в нём будет имя прописными буквами. Это условие можно привести к такому виду:
> 
> ```js
> allFields.forEach((someField) => {
>   if (someField.tagName === 'IMG' && !someField.src || !someField.textContent) {
>     someField.classList.add('hidden');
>   }
> });

Так теперь работает, но только с text.Content. Класс hidden добавляется и убирается в зависимости от содержимого. 
А вот img получается с классом hidden не зависимо от того, есть или нет src. Я даже добавила else {
    someField.classList.remove('hidden');
  } - не помогло.

2021-11-01 22:12 UTC, ArtemVeremienko commented on js/generate-elements.js
> +
@DariaAkimova запуш последнюю версию, чтобы я смогу посмотреть в чём может быть проблема.

2021-11-02 17:22 UTC, ArtemVeremienko requested changes
Исправь пару деталей и идём дальше 😄

2021-11-02 17:22 UTC, ArtemVeremienko commented on js/generate-elements.js
> +});
В блоке `else` удаляем класс `hidden` если не выполняется условие, то есть фото которые ты скрывала в `offerCardFragment` здесь показываем 😄 

В текущем условии мы также скрываем все иозбражения с соурсом, а это не подходит. Поэтому нужно уточнить условие:

```suggestion
allFields.forEach((someField) => {
  if (
      (someField.tagName === 'IMG' && !someField.src) ||
      (someField.tagName !== 'IMG' && !someField.textContent)
  ) {
      someField.classList.add('hidden')
  }
})
```

2021-11-02 17:22 UTC, ArtemVeremienko commented on js/generate-elements.js
> +const similarOffers = createAllOffers;
`createAllOffers` выглядит как функция, но в этой переменной массив оферов. Можно сразу экспортировать `similarOffers` или переименовать в `allOffers`.

2021-11-03 18:20 UTC, merged