Правда или действие (часть1)
htmlacademy-javascript/1652259-keksobooking-24 pull request #6
Opened 2021-11-05 20:34 UTC by DariaAkimova

2021-11-05 20:51 UTC, DariaAkimova commented on index.html
> +          <input id="address" name="address" type="text" readonly required>
В задании и тз не сказано, что поле с адресом обязательное, только что ручное редактирование поля запрещено. Я сделала обязательным, чтобы настроить валидацию, но не помогло. 
Оно и без атрибута required выдавало ошибку при отправке пустой формы, т.е. где-то это required уже было указано, но я не поняла где. 
Вообще значения в это поле буде подставляться  уже на этапе работы с картой. Думаю, надо убрать ву этого поля required, и разбираться с ним позже.

2021-11-05 20:51 UTC, DariaAkimova commented on js/form.js
> +
Попыталась сделать так, чтобы при отправке формы сразу у всех незаполненных обязательных полей появлялось сообщение, что их надо заполнить. Не сработало. Это, вроде, не обязательно, но как-то сделать можно ведь. Мой вариант:

const submitButton = document.querySelector('.ad-form__submit');

submitButton.addEventListener('click', () => {
  const allInputs = document.querySelectorAll('input');
  allInputs.forEach((input) => {
    input.addEventListener('invalid', () => {
      if (input.validity.valueMissing) {
        input.setCustomValidity('Поле должно быть заполнено');
      }  else {
        input.setCustomValidity('');
      }
    });
  });
});

2021-11-05 20:51 UTC, DariaAkimova commented on js/form.js
> +
Как можно сделать, чтобы все-таки при незаполненном поле сообщение об ошибке было мое (куда написать это setCustomValidity)? Если в итоге обработчик invalid я удалила, оставила только input.
Меня и такой вариант устраивает, просто интересно.

2021-11-05 20:55 UTC, DariaAkimova commented on js/form.js
>  );
Такой вариант валидации поля с адресом не работает, все равно форма отправляется с пустым адресом и появляется страница с ошибкой.
Думаю, что когда будем работать с картой, поле с адресом не сможет быть пустым, хоть какие-то координаты туда переданы будут. А пока на этом этапе ни в задании, ни в тз не сказано, что надо настраивать и это поле тоже.

2021-11-07 11:08 UTC, ArtemVeremienko requested changes
Молодец, все основные моменты сделала!

Есть [хороший туториал по валидации форм](https://developer.mozilla.org/ru/docs/Learn/Forms/Form_validation), в конце показан пример валидации JS'ом при сабмите

2021-11-07 11:08 UTC, ArtemVeremienko commented on js/form.js
> +
Не совсем понял вопрос, сообщение об ошибке указано правильно:
`priceInput.setCustomValidity (`Цена за ночь не может превышать ${MAX_PRICE}`);`

событие `invalid` вызываетя при:
- переод сабмитом формы
- после проверки валидации методами `checkValidity/reportValidity`

2021-11-07 11:08 UTC, ArtemVeremienko commented on js/form.js
>  );
В этом варианте ничего не вызывает событие `invalid`, потому что поле `readonly`

2021-11-07 13:19 UTC, DariaAkimova commented on js/form.js
> +
Так лучше?

form.addEventListener('submit', (evt) => {
  evt.preventDefault();

  allInputs.forEach((input) => {
    input.addEventListener('invalid', () => {
      if (!input.validity.valid) {
        input.setCustomValidity('Ошибка заполнения формы');
      } else {
        input.setCustomValidity('');
      }
      input.reportValidity();
    });
  });
});

2021-11-07 13:23 UTC, DariaAkimova commented on js/form.js
> +
Только я не очень поняла, зачем тогда нужна дополнительная валидация всей формы при отправке. Ведь если есть незаполненные поля или другое несоответствие, форма все равно не отправится и сообщения об ошибке в соответствующих полях появятся.

2021-11-07 14:22 UTC, ArtemVeremienko commented on js/form.js
> +
Еще можно вынести все слушатели за обработчик формы, например:
```js
allInputs.forEach((input) => {
  input.addEventListener('invalid', () => {
    if (!input.validity.valid) {
      input.setCustomValidity('Ошибка заполнения формы');
    } else {
      input.setCustomValidity('');
    }
    input.reportValidity();
  });
});

form.addEventListener('submit', (evt) => {
});
```

2021-11-07 14:23 UTC, ArtemVeremienko commented on js/form.js
> +
> зачем тогда нужна дополнительная валидация всей формы при отправке. Ведь если есть незаполненные поля или другое несоответствие, форма все равно не отправится и сообщения об ошибке в соответствующих полях появятся.

А как нам проверить `readonly` поле?

2021-11-07 15:07 UTC, DariaAkimova commented on js/form.js
> +
Мы же пока убрали readonly, оставили только required. 
А readonly будет проверяться, когда будет взаимодействие с сервером, пункт тз:
2.7. Если при отправке данных произошла ошибка запроса, показывается соответствующее сообщение.

2021-11-07 15:15 UTC, DariaAkimova commented on js/form.js
> +
> Еще можно вынести все слушатели за обработчик формы, например:
> 
> ```js
> allInputs.forEach((input) => {
>   input.addEventListener('invalid', () => {
>     if (!input.validity.valid) {
>       input.setCustomValidity('Ошибка заполнения формы');
>     } else {
>       input.setCustomValidity('');
>     }
>     input.reportValidity();
>   });
> });
> 
> form.addEventListener('submit', (evt) => {
> });
> ```

А так  input.setCustomValidity('Ошибка заполнения формы'); перебивает мою setCustomValidity на ввод.
Получается, что ввожу название, а вместо "Необходимо ввести еще .. символов" выводится "Ошибка заполнения формы".

Зачем выносить это за обработчик формы? Мы же в данном случае проверяем все поля именно в момент отправки. А до этого работают обработчики 'input'.

2021-11-07 22:04 UTC, ArtemVeremienko commented on js/form.js
> +
> А так input.setCustomValidity('Ошибка заполнения формы'); перебивает мою setCustomValidity на ввод.
Получается, что ввожу название, а вместо "Необходимо ввести еще .. символов" выводится "Ошибка заполнения формы".

Это случается из-за перезаписи `setCustomValidity`, как было перед этим вариантом. пока что можешь убрать проверку всех инпутов на валидность, а оставить выборочную для нужных полей.

> Зачем выносить это за обработчик формы? Мы же в данном случае проверяем все поля именно в момент отправки. А до этого работают обработчики 'input'.

Событие `invalid` возникает передо отправкой формы, а когда обработчики устанавливаются внутри сабмита они не смогут отловить событие которое уже случилось.

> Мы же пока убрали readonly, оставили только required.
А readonly будет проверяться, когда будет взаимодействие с сервером, пункт тз:
2.7. Если при отправке данных произошла ошибка запроса, показывается соответствующее сообщение.

Сейчас да, но в следующем шаге нужно будет добавить readonly и убрать required (он не будет работать). И чтобы не отправить пустое поле нужно будет проверять его при сабмите.

2021-11-07 22:08 UTC, ArtemVeremienko commented
В примерах на уроке и демострациях сначла показывают вариант с `invalid`, который будет вызываться перед сабмитом или вызовом валидации с JS, а затем предлагают добавить отображение валидации при вводе `input`. Поэтому нужно выбрать один из этих способов как будем отображать ошибку валидации. Если использовать сразу 2 то сначала сработает `input` и если будет невалидным `invalid`, который перезатрёт наше сообщенгие с `setCustomValidity`.

2021-11-08 07:55 UTC, DariaAkimova commented on js/form.js
> +
А если добавлять полю с адресом required только тогда, когда его пытаются отправить пустым? 

addressInput.addEventListener('submit', () => {
  if (addressInput.value === ' ') {
   addressInput.setAttribute('required', 'true');
}
});
Это я уже убрала equired из разметки и добавила туда readonly.

Тогда addressInput  станет invalid и попадет под обработчик для всех импутов. Я только не понимаю, как это объединить, если событие 'submit' происходит после события 'invalid'. Получается, что addressInput станет invalid уже после того, как все импуты пройдут эту проверку 
allInputs.forEach((input) => {
  input.addEventListener('invalid', () => { ...... 

Или этот вариант вообще не вариант?

2021-11-08 07:59 UTC, DariaAkimova commented on js/form.js
> +
Все, у меня нет идей, как не дать отправить пустое поле readonly. Если я его не указываю обязательным, оно все равно уходит на сервер, и уже там выдает ошибку. Подскажи, пожалуйста.

2021-11-08 12:26 UTC, DariaAkimova commented
> В примерах на уроке и демострациях сначла показывают вариант с `invalid`, который будет вызываться перед сабмитом или вызовом валидации с JS, а затем предлагают добавить отображение валидации при вводе `input`. Поэтому нужно выбрать один из этих способов как будем отображать ошибку валидации. Если использовать сразу 2 то сначала сработает `input` и если будет невалидным `invalid`, который перезатрёт наше сообщенгие с `setCustomValidity`.

Я и хочу оставить отображать ошибку валидации только при вводе. Но тогда что делать с адресом, который readonly?

2021-11-09 07:31 UTC, ArtemVeremienko commented on js/form.js
> +
> А если добавлять полю с адресом required только тогда, когда его пытаются отправить пустым?

Атрибуты, в основном, используются для начального состояния. Лучше напрямую работать со свойствами элемента. Когда происходит сабмит, это означает что всё валидное и добавление атрибута не запустит валидацию.

> allInputs.forEach((input) => {
input.addEventListener('invalid', () => { ......
Или этот вариант вообще не вариант?

В этом заданию нужно проверять только некоторые поля. Думаю цикл по всем инпутам может быть излишним :slightly_smiling_face: 

> Все, у меня нет идей, как не дать отправить пустое поле readonly. Если я его не указываю обязательным, оно все равно уходит на сервер, и уже там выдает ошибку. 

Этот вариант почти правильный, только в инпуте нет события `submit` и нужно отменить сабмит при невалидном поле
```js
formElement.addEventListener('submit', () => {
  if (!addressInput.value) {
    // при невалидном поле отменить сабмит
  }
});
```

2021-11-09 07:32 UTC, ArtemVeremienko commented
> > В примерах на уроке и демострациях сначла показывают вариант с `invalid`, который будет вызываться перед сабмитом или вызовом валидации с JS, а затем предлагают добавить отображение валидации при вводе `input`. Поэтому нужно выбрать один из этих способов как будем отображать ошибку валидации. Если использовать сразу 2 то сначала сработает `input` и если будет невалидным `invalid`, который перезатрёт наше сообщенгие с `setCustomValidity`.
> 
> Я и хочу оставить отображать ошибку валидации только при вводе. Но тогда что делать с адресом, который readonly?

его нужно обработать в сабмите. Например как здесь: https://developer.mozilla.org/ru/docs/Learn/Forms/Form_validation#a_more_detailed_example

2021-11-09 18:26 UTC, merged