Надо подкачаться
htmlacademy-javascript/1652259-keksobooking-24 pull request #9
Opened 2021-11-12 10:54 UTC by DariaAkimova

2021-11-13 20:14 UTC, ArtemVeremienko requested changes
Всё хорошо, уже разобралась с колбэками, которых боялась в начале.

Сейчас возникает ошибка при создание карточек. В данных которые приходят может не быть, например
- features
- photos
 и т.д. Нужно правильно обработать эти моменты.

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/api.js
> +    });
добавь лог ошибок, чтобы проще определить где искать
```suggestion
    .catch ((err) => {
      console.error(err);
      onFail(err);
    });
```

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/generate-elements.js
> +    });
давай попробуем это всё сделать через `forEach`, `some` - здесь можно не использовать

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/api.js
> +};
не убираем слушатели после закрытия сообщения

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/api.js
> +}; //нам надо, чтобы при успешной отправке данных и сообщение открывалось, и все поля очищались. Можно вставить clearAll коллбэкком?
не убираем слушатели после закрытия сообщения

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/api.js
> +      () => showErrorMessage,
здесь не вызывается функции. при вызове колбеков просто возвращаем имя функций

2021-11-13 20:14 UTC, ArtemVeremienko commented on js/api.js
> +  //Или как это лучше реализовать?
> нам надо, чтобы при успешной отправке данных и сообщение открывалось, и все поля очищались. Можно вставить clearAll коллбэкком?

в колбек `onSuccess()` можно передать функцию, которая будет вызывать открытие сообщений и очистку полей.

2021-11-14 07:28 UTC, DariaAkimova commented on js/main.js
> +const ALERT_SHOW_TIME = 100000;
Про это сообщение в тз не сказано ничего про время, я для себя пока оставила так, чтобы было нагляднее. Потом сделаю меньше.
5.2. Если при загрузке данных с сервера произошла ошибка запроса, нужно показать соответствующее сообщение. Дизайн блока с сообщением нужно придумать самостоятельно. - про время не сказано

2021-11-14 07:36 UTC, DariaAkimova commented
> Всё хорошо, уже разобралась с колбэками, которых боялась в начале.
> 
> Сейчас возникает ошибка при создание карточек. В данных которые приходят может не быть, например
> 
> * features
> * photos
>   и т.д. Нужно правильно обработать эти моменты.

Я проверяла наличие этих данных и просто сравнивая их со своими из data.js, и этими способами:

console.log (offers[0].offer.features === undefined) //false
console.log (offers[0].offer.photos === undefined) //false 
Значит, features и photos на месте. Так ведь?

console.log (Array.isArray (offers[0].offer.features) //true
console.log (Array.isArray(offers[0].offer.photos) //true
Значит, это массивы, и к ним можно применить forEach

Что я могу упускать? Как это еще лучше проверить?

2021-11-14 07:45 UTC, DariaAkimova commented on js/generate-elements.js
> +  return [...offerCardFragment.children];
Я пока что закомментировала все, что относится к features и photos. Раньше без них функция renderSimilarOffers выдавал undefined. Я добавила return, теперь then.onSuccess() работает как надо. Осталось наладить отрисовку карточек и разобраться с features и photos.

2021-11-14 08:04 UTC, DariaAkimova commented on js/api.js
> +};
errorMessage или successMessage, в зависимости от сообщения, которое открыто.

2021-11-14 08:14 UTC, DariaAkimova commented on js/generate-elements.js
> +    });
Но тут ведь логика такая, что в результате перебора массива features должно возвращаться true, если хоть один элемент соответствует условиям. И тогда соответствующий featureItem отобразится в карточке. 
Почему тогда тут не подходит some?

2021-11-14 18:03 UTC, DariaAkimova commented on js/api.js
> +  document.body.removeChild(typeOfMessage);
Временно поменяла добавление класса hidden на удаление элемента. Проверила в консоли: 
document.body.children // ... .... ... div.success .. .. ...  - сообщение об удалении есть в числе детей
Но при попытке удаления все равно выдает ошибку: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. 
Что-то я в случае сообщений об успехе и об ошибке не так делаю с DOM, видимо. Они выводятся, когда надо, но если пытаюсь их закрыть - в метах, где обработчики, появляется ошибка

2021-11-14 22:28 UTC, ArtemVeremienko commented on js/api.js
> +};
тогда лучше указать что мы передаём элемент сообщения, а не тип)

2021-11-14 22:30 UTC, ArtemVeremienko commented on js/main.js
> +const ALERT_SHOW_TIME = 100000;
Просто было интересно почему ты выбрала такую длительность. Сколько секунд будет показываться сообщение?)

2021-11-14 22:38 UTC, ArtemVeremienko commented on js/api.js
> +  document.body.removeChild(typeOfMessage);
`removeChild` удаляет ребёнка, ошибка говорит, что ты пытаешь удалить не ребёнка `body`

2021-11-14 22:39 UTC, ArtemVeremienko commented
> Что я могу упускать? Как это еще лучше проверить?

Ты проверяешь только первый элемент, а их 50. В некотрых нет фото, в других фичей, в третих и тех и тех.

2021-11-15 06:34 UTC, DariaAkimova commented on js/api.js
> +  document.body.removeChild(typeOfMessage);
это я поняла) но как он может быть не ребенком body, когда до этого я его же добавила к body с помощью appendChild?

2021-11-15 06:48 UTC, DariaAkimova commented on js/generate-elements.js
> +
Надо было просто вовремя добавить это проверку... теперь с данными порядок

2021-11-15 19:32 UTC, ArtemVeremienko commented on js/generate-elements.js
> +    });
это как улучшение, давай пока оставим твою версию

2021-11-15 19:48 UTC, ArtemVeremienko commented
@DariaAkimova по этому заданию всё хорошо. Добавь недостающий функционал в форму добавления объявлений в следующем ПРе.

2021-11-15 19:49 UTC, merged